### ISSUE TITLE
dsptoolkit get-samplerate returns default 48000 on dac2 hd + DSP

### ISSUE THREAD

**Issue by tstupka** [hifiberry/hifiberry-dsp#43]
rpi3, dac2 hd + dsp
linux 5.10.78-2-osmc
dsptoolkit 0.20
dsp-addon-96-13.xml

`dsptoolkit get-samplerate` returns 48000Hz even though:

```
<?xml version="1.0" encoding="utf-8"?>
<ROM IC="ADAU1451" IC_Address="1" Address_byte_length="2">
        <dateTime>2020-12-08T12:44:00.3255070Z</dateTime>
        <version>4.5.0.1779</version>
        <beometa>
                <metadata type="sampleRate">96000</metadata>
                <metadata type="profileName">DSP add-on</metadata>
                <metadata type="profileVersion">13</metadata>
```

**Comment by ashtoncowie** [comment]
I know this issue was opened 9 months ago but I think I've solved this.
- Running `git grep -F samplerate` in repo root (notice the lowercase "r") returns lots of results of python functions that read and parse the sample rate. 
  - Most important of these is `hifiberrydsp/parser/xmlprofile.py:ATTRIBUTE_SAMPLERATE = "samplerate"` 
    - i.e. **the actual XML attribute that gets read is indeed "samplerate" with a lowercase "r".** 
- `git grep -F sampleRate` with a capital "R" only returns three sample XML files, and nothing in the code itself!
  - It's worth noting that `dsptoolkit get-samplerate` [returns 48000](https://github.com/hifiberry/hifiberry-dsp/blob/39755280191c9cbe066288e3dfb34710c7a9db10/hifiberrydsp/dsptoolkit.py#L374) as a default value when it can't parse the metadata for whatever reason.

So this boils down to a typo in these sample XML files here, not to mention the profiles in [hifiberry-os](https://github.com/hifiberry/hifiberry-os) that most users have installed by default.

**Correcting this typo in my profile (I'm also using [dsp-addon-96-13](https://github.com/hifiberry/hifiberry-os/blob/master/buildroot/package/dspprofiles/dsp-addon-96-13.xml)) and installing it fixed it for me.** 

Once I have a minute I'll open PRs for this.
